name: Test Simple Workflow

on:
  push:
    branches:
      - main  # Déclenchement sur un push vers la branche "main"

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Afficher un message
        run: echo "Hello, World!"
