name: Send Match Email

on:
  schedule:
    - cron: '0 7 * * *'  # Tous les jours à 9h Paris (UTC+2)
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    env:
      MAIL_USER: ${{ secrets.MAIL_USER }}
      MAIL_PASS: ${{ secrets.MAIL_PASS }}
      FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: python main.py
